modLoader="javafml"
loaderVersion="[35,)"
license="GNU GPLv3"

[[mods]]
modId="obsidiansword"
version="${file.jarVersion}"
displayName="Obsidian Sword"
credits="hsabbas"
authors="hsabbas"

description='''
This mod adds an obsidian sword to the game. It does incredible damage but breaks after only one hit.

Smelt obsidian for obsidian shards and combine four shards in a square to create a refined obsidian shard to make a sword.
'''

[[dependencies.obsidiansword]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"

[[dependencies.obsidiansword]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4,1.17)"
ordering="NONE"
side="BOTH"
